FROM node:10.14.2-alpine
LABEL maintainer="Mehrad Rafigh <mehrad at rafigh dot de>"

RUN mkdir -p /var/www/html/dist
WORKDIR /var/www/html

EXPOSE 4000

COPY dist/ dist

CMD node dist/apps/fosdem/server.js
